name: my-test-ubuntu-shell-command

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: test
      id: test
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        df -hT $PWD
        echo '以便每次将提交推送到名为 main 的分支时，工作流都会自动运行' > 1.txt
        cp 1.txt $PWD
        echo "::set-output name=status::success"
    - name: Upload file directory
      uses: actions/upload-artifact@main
      if: steps.test.outputs.status == 'success' && !cancelled()
      with:
        name: 1.txt
        path: $PWD
