name: my-test-ubuntu-shell-command

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: test
      id: test
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        mkdir sh2288
        cd sh2288
        echo '以便每次将提交推送到名为 main 的分支时，工作流都会自动运行' > 1.txt
        echo '哈哈哈哈' > 2.txt
    - name: Upload file directory
      uses: actions/upload-artifact@main
      with:
        name: upload-dir-sh2288
        path: sh2288
